### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xyroot** [seanwlk/warface-crate-manager#1]
Awesome tool, didn't have to bother with the website anymore and just kept on playing, but here are a few suggestions which I think would be nice to have as well

### Timestamps
I think it would be a good idea to add a timestamp for each message printed in the console, since sometimes there are delays with the arrival of crates.

### Slot availability
Maybe a small portion at the bottom of the window can be used to display how many slots are available/taken or currently being opened

### Timer in main window
An estimated timer as to when the next crate will open, I say estimate so it wouldn't have to be refreshed per second, or can be just taken from the closest crate and creating a local timer

**Comment by seanwlk** [comment]
Timestamps: Legitimate request, i will add that in the next release.

Slot availability: that's why i made the crates window

Timer in main window: i dont think it's a good idea, same reason i won't add the slot availability thing. Imho it's better if main window that runs all the time, has less stuff as possible that could make it too heavy for the average user. If i start to add counters and live refreshes on that, people with bad PCs would suffer and same for continuous HTTP requests. The python code itself is not efficient already (coz im bad) plus the executable makes it even worst.

**Comment by xyroot** [comment]
I see, makes sense as to why each feature was separated from the main window.

Another one, I know it's scheduled to do an http request, but at what frequency? I noticed because I checked the site and the crate was there but the manager didn't catch it as it arrived. But it opened it after a few mins
In relation to this, how about a manual refresh button to force an http request to recheck again?

Thanks for checking this out by the way, didn't expect you'd take notice

**Comment by seanwlk** [comment]
The current delay is 30seconds after each request for the main window. Every other window sends one single request every time you open it.

I must admit that at first i attempted to add a refresh button in each window but then i realized that the way i made this application is so stupid that to do it it would have to destroy the window and open it again since when the components of the window are created they are static. I'd have to redesign how i made it but i had it in plan. Can't promise anything.


PS
i already got asked about a customization setting in order to chose sync time. Making the menu itself is not a problem, but making it only for one small setting looks bad for me, when i'll find something else that would be useful to be customized i'll probably make it so that it will save the settings in a file like the credentials one (or even the same at this point)

**Comment by xyroot** [comment]
### Armageddon Features.
Now I know this was originally a Crate Manager tool but the Armageddon context menu gave me an idea to kinda expand its capabilities for Armageddon BP as well, but it might drive the tool into an Armageddon oriented toolkit, I just hate going to the site.

1. **Task completion messages daily/weekly**  - message log printing if a task was completed either daily/weekly + how much XP was earned (optional)
2. **Task Progression Updates** - might be repetitive; message print stating progress was recorded for a particular task, even percentage (but extra coding work so probably no)
3. **Personal Armageddon Crate** - printing the acquisition of personal crates, and maybe even opening them -- not sure if it's the same http request.
4. **Base Research** - printing if done or in progress, I don't know, I haven't unlocked it yet but might be nice to have. Maybe in its own context menu in Armageddon too.

**Comment by seanwlk** [comment]
The tasks are in different for the same reason as crates. Each week has a different endpoint and would end up in countless requests.

About base research, I sort of did the math and it's not worth implementing it since basically after 1st day, you can basically send a research once a day.

About personal crates, they are currently in the profile menu, but sicne when I made it I basically "imagined" how it was supposed to work I didn't enchant it further. I could now make a button that opens the crates at once and displays the results

**Comment by seanwlk** [comment]
Partial implementation of the request. I believe that it's fair enough.

**Comment by xyroot** [comment]
This is awesome, thanks!

**Comment by seanwlk** [comment]
> This is awesome, thanks!

Wait for a release, some of that stuff is still broken because i found out that base upgrade changes the research missions.
