### ISSUE TITLE
Brother Can we use base research i have downloaded version 1.7 but its now showing to reserch in base 

### ISSUE THREAD

**Issue by Tharumax** [seanwlk/warface-crate-manager#3]
Brother Can we use base research I have downloaded version 1.7 but it's now showing to research in the base . pls explain bro it a very painful thing to open research every 20 minutes

**Comment by seanwlk** [comment]
Hello,
sorry that's my fault, i designed it by looking at my account. I assume you have level 1 base. Basically what happens is that I'm displaying both buttons for starting research but when you are level 1 you have only short research so it ends up not showing anything at all because it goes in error.

I will fix it ASAP and push a new release.

**Comment by seanwlk** [comment]
Hi, i pushed a commit that should fix this issue for users with base level = 1.

I updated the release package without pushing an actual update. Just download the one Zip. Or `git pull` if you are running non-compiled version.

**Comment by Tharumax** [comment]
ok thax
